development:
  adapter: mysql2
  encoding: utf8
  database: 
  username: 
  password: 
  host: 
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: 
  username: 
  password: 
  host: 
  port: 3306