native_client: youplay://
player_width: 800
player_height: 475
videos_per_channel: 10
upload_pass: 
developer_key:
secret_token: 
device_secret:
imprint:
root:
SENDGRID_USERNAME:
SENDGRID_PASSWORD:

#heroku config:set native_client=youplay:// player_width=800 player_height=475 videos_per_channel=10 upload_pass= developer_key= secret_token= devise_secret= imprint= root= SENDGRID_USERNAME= SENDGRID_PASSWORD=